language: ruby
before_install:
  - gem install bundler -v '1.17.2'
gemfile:
  - Gemfile
rvm:
  - 2.5.9
  - 2.6.9
  - 2.7.5
  - 3.0.2
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
script:
  - bundle exec rspec spec
